
package org.lavlad.wslab.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BookNotFoundException", targetNamespace = "http://service.wslab.lavlad.org/")
public class BookNotFoundException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BookNotFoundFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BookNotFoundException(String message, BookNotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BookNotFoundException(String message, BookNotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.lavlad.wslab.service.BookNotFoundFault
     */
    public BookNotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
